# Generated by Django 5.2.4 on 2025-07-12 08:48

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Акцент',
                'verbose_name_plural': 'Акценты',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('url', models.URLField(verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
            },
        ),
        migrations.CreateModel(
            name='PostBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.SlugField()),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('number_epis', models.PositiveSmallIntegerField(verbose_name='Номер эпизода')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('url', models.SlugField(verbose_name='Ссылка')),
                ('video', models.FileField(upload_to='', verbose_name='Видео')),
                ('script', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('accent', models.ManyToManyField(related_name='accent_related', to='home.accent', verbose_name='Акцент')),
                ('author', models.ManyToManyField(related_name='author_related', to='home.author', verbose_name='Автор')),
                ('level', models.ManyToManyField(related_name='lvl_related', to='home.level', verbose_name='Уровень')),
                ('topic', models.ManyToManyField(related_name='topic_related', to='home.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
            },
        ),
        migrations.CreateModel(
            name='DiscusBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название фильма')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('episodes', models.ManyToManyField(related_name='ep_related', to='home.episode', verbose_name='Эпизод')),
                ('level', models.ManyToManyField(related_name='lvl_movie', to='home.level', verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='RightOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.episode')),
            ],
        ),
        migrations.CreateModel(
            name='SubStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('bef_one', models.CharField(max_length=200, verbose_name='before first')),
                ('bef_two', models.CharField(max_length=200, verbose_name='before second')),
                ('bef_three', models.CharField(max_length=200, verbose_name='before third')),
                ('aft_one', models.CharField(max_length=200, verbose_name='after first')),
                ('aft_two', models.CharField(max_length=200, verbose_name='after second')),
                ('aft_three', models.CharField(max_length=200, verbose_name='after third')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.episode')),
            ],
        ),
        migrations.CreateModel(
            name='TestCinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('first', models.CharField(max_length=100, verbose_name='Первый ответ')),
                ('second', models.CharField(max_length=100, verbose_name='Второй ответ')),
                ('third', models.CharField(max_length=100, verbose_name='Третий ответ')),
                ('correct', models.SmallIntegerField(verbose_name='Правильный ответ')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.episode')),
            ],
        ),
    ]
