# Generated by Django 5.2.4 on 2025-08-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_postblog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_cover',
            field=models.ImageField(default=1, upload_to='', verbose_name='Обложка для видео'),
            preserve_default=False,
        ),
    ]
